package: suitesparse

platform:
  - linux-64
  #- linux-32
  #- osx-64
  #- win-32
  #- win-64

install:
  - conda config --set always_yes true

script:
  - conda config --add channels zeehio
  - conda build .

build_targets:
  files: conda
  channels: main
